package com.esprit;

import static com.codename1.ui.CN.*;

import com.codename1.ui.Dialog;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Toolbar;

import com.gui.ListLivraisonForm;
import com.services.CodeScan;

import com.codename1.ui.Form;
import com.codename1.ui.layouts.BoxLayout;

import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.gui.Home;
import com.gui.Map;
import com.gui.Rate;




/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
//        Form home = new Form("Hi World", BoxLayout.y());
//        Button afficheBtn = new Button("Livraison");
//        Button scanBtn = new Button("Scan");
//        home.add(afficheBtn);
//        home.add(scanBtn);
//       
//       new Map().show();
//    new ListLivraisonForm().show();
//new CodeScan().show();
        new Home().show();
//     new Rate().show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
